### ISSUE TITLE
Todos for second milestone

### ISSUE THREAD

**Issue by shaiguitar** [ArnoBen/datamining_itc#1]
- [x] @ArnoBen Add CLI options 

Types: be able to get artist / album / song / genre ) 
Options : year query

- [ ] Add option to store the data into a DB. ONLY NEW DATA ...
- [x] @shaiguitar dedicated py script to create db structure
- [x] @shaiguitar docs for table etc
- [x] @ArnoBen Docs for argparse/click
- [x] @ArnoBen Add click or argparse
- [x] ERD for mysql
- [ ] (optional) Add ORM? sqlalchemy

**Comment by shaiguitar** [comment]
![ERD-discogs.pdf](https://github.com/ArnoBen/datamining_itc/files/9181456/ERD-discogs.pdf)
